# Generated by Django 3.1.7 on 2021-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tech Stack'),
        ),
    ]
